#Uncomment this line to define a global platform for your project
platform :ios, '8.0'
pod 'AFNetworking', '~> 2.5'
pod 'MBProgressHUD', '~> 0.9'

target 'MacysExample' do

end

target 'MacysExampleTests' do

end

